name: RetroArch

on:
  push:
    paths:
      - 'homebrew/RetroArch/**'
    tags:
      - '*'
  pull_request:
    paths:
      - 'homebrew/RetroArch/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install bash clang-18 lld-18
          sudo apt install build-essential cmake pkg-config wget 7zip

      - name: Install toolchain
        run: |
          wget https://github.com/ps5-payload-dev/pacbrew-repo/releases/latest/download/ps5-payload-dev.tar.gz
          sudo tar xf ps5-payload-dev.tar.gz -C /

      - name: Build
        run: |
          PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk ./homebrew/RetroArch/build.sh
          PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk ./homebrew/RetroArch/build-fceumm.sh
          PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk ./homebrew/RetroArch/build-snes9x2010.sh
          PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk ./homebrew/RetroArch/build-genesis_plus_gx.sh
          PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk ./homebrew/RetroArch/build-mednafen_gba.sh
          PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk ./homebrew/RetroArch/build-vice.sh
          PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk ./homebrew/RetroArch/build-puae2021.sh
          ./homebrew/RetroArch/fetch-assets.sh

      - name: Zip build output
        run: |
          cd homebrew
          zip -r ../RetroArch.zip RetroArch

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: RetroArch
          path: RetroArch.zip
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: RetroArch
          path: .

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: true
          files: RetroArch.zip

